## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  - osx

julia:
  - 1
  - 1.5
  - nightly

notifications:
  email: false

before_install:
  - git clone --single-branch https://github.com/ceed/libceed
  - pushd libceed
  - make
  - export JULIA_LIBCEED_LIB=$(find $PWD/lib -name "libceed*")
  - popd

jobs:
  allow_failures:
    - julia: nightly
